[package]
name = "typebeat-dot-xyz"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typebeat = { path = ".." }

[[bin]]
name = "typebeat-dot-xyz"
path = "main.rs"
